# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67f7d7e80507624cf40b71bfa403e8a2142116044b6235541b56b27e6736bfd9c4216b78a6602a7deb2204e67b54f48d601330341f2171e5be53fb87a83d2d8

test:
  secret_key_base: a363f282400d18760461b3b51b1974f0431b80d9c760c05ffcea56e2940c761e2321e1af630c20cea496682d086d7877ac5689bf1534039a0743ac3a6b2a489d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
